### PR TITLE
Updated recipe/meta.yaml to version 3.15.0

### PR DESCRIPTION
**Pull request by jochym**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Can we squash merge this when it goes in?

**Comment by CJ-Wright** [comment]
Also it seems that conda-forge may need a flask feedstock.

**Comment by jochym** [comment]
Of course we can squash-merge @CJ-Wright  ! The flask is indeed a problem. I finally (!) narrowed it down to flask 0.10 for py<36. There is a flask feedstock but it seems to have a problem below py36. I do not understand it fully - the name seems strange (py_2 for all versions). If you know a better solution I will be happy to use it.

**Comment by CJ-Wright** [comment]
It seems that the flask dep is being pulled from defaults not conda-forge. The defaults channel is a bit slower to update than conda-forge (hence why we might try to make a flask feedstock).

**Comment by jochym** [comment]
There is a flask feedstock. I just created re-rendering PR in there (https://github.com/conda-forge/flask-feedstock/pull/10).

**Comment by CJ-Wright** [comment]
Hmm, google missed that when I searched for it. :sheep:

**Pull request merged**
