### PR TITLE
MNT: Re-rendered with conda-smithy 1.7.0

### PR DESCRIPTION
**Pull request by CJ-Wright**
python 3.6

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge/ase Ready for review/merge!

**Comment by jakirkham** [comment]
Some of the files have executable permissions here too. 😕 Could you please try re-rendering again?

**Comment by jochym** [comment]
I have added @CJ-Wright to maintainers and re-rendered the package again. Merged in other PR (https://github.com/conda-forge/ase-feedstock/pull/3). Closing this one as redundant. You can re-open it if there is something extra I have missed.

**Comment by jakirkham** [comment]
I'd really curious to know what happened in the re-rendering, @CJ-Wright . If you please could open an issue at `conda-smithy` documenting your steps and environment information, that would be very helpful for determining what the underlying issue is.

**Comment by CJ-Wright** [comment]
@jochym Thank you!
@jakirkham I will open an issue.

**Pull request closed without merging**
