### PR TITLE
WIP: Try to clean up the feedstock after conversion

### PR DESCRIPTION
**Pull request by jochym**

### CODE REVIEW

**Comment by jochym** [comment]
@conda-forge-admin, please rerender

**Comment by jochym** [comment]
@conda-forge-admin, please rerender

**Comment by jochym** [comment]
@conda-forge-admin, please add noarch: python

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by jakirkham** [comment]
Pushed a merge commit with `master`. This seems to have gotten rid of AppVeyor. However CircleCI is missing. Could you please double check your settings with CircleCI to make sure it has access to your repos? If that all looks correct, would try revoking CircleCI permissions and readding them.

**Comment by jochym** [comment]
Will check. Thanks for your help. It may be that CCI lost the access due to some problems on their side.

**Comment by jochym** [comment]
@jakirkham I think the webhook for CCI got deleted somehow. But I do not think I can add it back. I do not have access to the project settings. Do you ?

**Comment by jakirkham** [comment]
Just checked, webhook is there.

Could you please read this doc PR ( https://github.com/conda-forge/conda-forge.github.io/pull/554 ) and try any suggestions it has? The user who wrote that had the same issue recently and fixed it. Also if anything in particular works or doesn't would be great to have that as feedback in that doc PR as well. Thanks.

**Pull request closed without merging**
